# Generated by Django 4.2.7 on 2023-11-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workemail', models.CharField(max_length=200, verbose_name='Work Email')),
                ('city', models.CharField(blank=True, choices=[('COSPRGS', 'Colorado Springs'), ('DEN', 'Denver'), ('PBLO', 'Pueblo'), ('NRGLN', 'Northglenn'), ('LNGMT', 'Longmont'), ('MONT', 'Montrose')], max_length=100)),
            ],
        ),
    ]
