# Generated by Django 4.2.7 on 2023-11-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='title',
        ),
    ]
