# Generated by Django 4.2.7 on 2023-11-27 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_calendar_counselor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarInCounselors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.counselor')),
                ('counselors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.calendar')),
            ],
        ),
    ]
