# Generated by Django 4.2.7 on 2023-11-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_calendarincounselors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarInCounselors',
        ),
    ]
